import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbarz from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Video Background */}
        <div className="absolute inset-0 -z-10">
          <video
            className="w-full h-full object-cover"
            src="/test.mp4"
            autoPlay
            loop
            muted
          />
          {/* Black Overlay */}
          <div className="absolute inset-0 bg-black/50" />
        </div>

        {/* Main Content */}
        <div className="flex flex-col min-h-screen relative">
          {/* Navbar */}
          <div className="fixed top-0 left-0 w-full z-10">
            <Navbarz />
          </div>

          {/* Scrollable Content */}
          <main className="flex-grow mx-auto w-full z-0 scroll-auto">
            {children}
          </main>

          {/* Footer */}
          <div className="w-full z-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
